è possibile verificare se le curve di Gumbel interpolano meglio i dati forniti per durate di tempo più corte dell'ora.

In [1]:
import os
import math
from pandas import *
import pandas as pd
from datetime import datetime
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('PluviometriaMin.txt')

In [3]:
map(datetime,data['anno'])
data=data.set_index('anno')

In [4]:
data

      15min  30min  45min
anno
2000   20.8   29.6   32.6
2001   22.2   31.2   34.8
2002   26.2   36.6   41.0
2003   15.8   20.8   25.4
2004   13.6   18.6   19.2
2005   28.2   48.2   53.6
2006   18.0   24.4   30.8
2007   28.6   39.0   57.8
2008   18.6   34.4   43.8
2009   24.6   44.6   61.2
2010   16.2   28.2   42.2
2011   15.8   17.8   21.0
2012   15.8   18.6   18.6
2013    7.2    8.8    9.6
2014   32.2   55.4   67.2
2015   14.2   21.0   24.0
2016   23.8   36.0   38.4
2017   22.6   35.4   44.0
2018   10.0   18.0   20.8
2019   25.0   28.6   30.6
2020   25.0   42.2   65.2
2021   20.2   28.0   30.6

In [6]:
means=data.mean()
variances=data.var()
stds=data.std()
cv=data.std()/means
EulerGamma=0.577215664901532860606512090

In [7]:
coeff1 = (math.sqrt(6)/math.pi)
coeff2= coeff1*EulerGamma

In [8]:
def g(m,s):
    return pd.DataFrame([m-coeff2*s,coeff1*s],index=["a","b"])

In [18]:
ab_m = g(means, stds)
ab_m
ab_m.to_pickle("ab_mMin")

In [19]:
from scipy.stats import genextreme,gumbel_r
from numpy import linspace

In [20]:
def gumbel(x,abs_d,col):
    return np.exp(-np.exp(-(x-ab_m[col]["a"])/ab_m[col]["b"]))

In [21]:
from statsmodels.distributions.empirical_distribution import ECDF
import numpy as np

In [22]:
min= data.min()[0]
max = data.max()[2]
t_rain=np.linspace(min, max,100)

In [26]:
gb=pd.DataFrame([gumbel(t_rain,ab_m,"15min"),
                 gumbel(t_rain,ab_m,"30min"),
                 gumbel(t_rain,ab_m,"45min")]).T
gb.index=t_rain
gb.columns=["15min","30min","45min"]
gb

              15min     30min     45min
7.200000   0.000375  0.000605  0.002727
7.806061   0.000936  0.000984  0.003596
8.412121   0.002099  0.001550  0.004681
9.018182   0.004287  0.002370  0.006018
9.624242   0.008061  0.003523  0.007646
...             ...       ...       ...
64.775758  0.999934  0.988308  0.939930
65.381818  0.999942  0.989071  0.942661
65.987879  0.999949  0.989784  0.945272
66.593939  0.999955  0.990451  0.947767
67.200000  0.999960  0.991074  0.950151

[100 rows x 3 columns]

In [1]:
csfont = {'fontname':'Times New Roman'}
plt.rc('xtick', labelsize=10)
plt.rc('ytick', labelsize=10) 
plt.style.use('default')
ax=gb.plot(color=["red","blue","magenta","limegreen","orange"])
ecdf1h = ECDF(data["1h"])
ax.plot(data["1h"],ecdf1h(data["1h"]),'+',c="red", label="1h",markersize=6) 
data3h=data["3h"]
ecdf3h = ECDF(data3h)
ax.plot(data3h,ecdf3h(data3h),"+",c="blue", label="3h",markersize=6)
data6h=data["6h"]
ecdf6h = ECDF(data6h)
ax.plot(data6h,ecdf6h(data6h),"+",c="magenta", label="6h",markersize=6)
data12h=data["12h"]
ecdf12h = ECDF(data12h)
ax.plot(data12h,ecdf12h(data12h),"+",c="limegreen", label="12h",markersize=6)
data24h=data["24h"]
ecdf24h = ECDF(data24h)
ax.plot(data24h,ecdf24h(data24h),"+",c="orange", label="24h",markersize=6)
plt.title('Curva di Gumbel',**csfont)
plt.xlabel('Rainfall [mm]',**csfont)
plt.ylabel('P[H < h]',**csfont)
#ax.set_xlabel('Rainfall [mm]', fontsize=10)
#ax.set_ylabel('P[H < h]')
ax.set_aspect('auto')
plt.legend(['1h', '3h', '6h', '12h', '24h'], loc='right',  title = "Legenda", title_fontsize = 10)

#major grid lines
plt.grid(b=True, which='major', color='gray', alpha=0.6, linestyle='dashdot', lw=0.5)
#minor grid lines
plt.minorticks_on()
plt.grid(b=True, which='minor', color='beige', alpha=0.8, ls='-', lw=1)

plt.show()

NameError: name 'plt' is not defined

In [ ]:
Per durate inferiori all